using System;
using System.Collections.Generic;
using System.Reflection;
//using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace P2B
{
	class MainColoreado
	{
		public static void MainColor()
		{
			/*Creamos las provincias*/
			Provincia hu = new Provincia(new Coordenada(4, 6), new Coordenada(5, 8));
			Provincia ca = new Provincia(new Coordenada(6, 8), new Coordenada(8, 9));
			Provincia se = new Provincia(new Coordenada(6, 5), new Coordenada(10, 7));
			Provincia ma = new Provincia(new Coordenada(9, 8), new Coordenada(16, 9));
			Provincia co = new Provincia(new Coordenada(11, 6), new Coordenada(16, 7));
			Provincia ja = new Provincia(new Coordenada(13, 3), new Coordenada(16, 5));
			Provincia gr = new Provincia(new Coordenada(17, 4), new Coordenada(19, 8));
			Provincia al = new Provincia(new Coordenada(20, 6), new Coordenada(22, 8));

			/*Creamos el mapa y le metemos todas las provincias*/
			Mapa mapa = new Mapa(new List<Provincia>());
			mapa.addProvincia(hu);
			mapa.addProvincia(ca);
			mapa.addProvincia(se);
			mapa.addProvincia(ma);
			mapa.addProvincia(co);
			mapa.addProvincia(ja);
			mapa.addProvincia(gr);
			mapa.addProvincia(al);

			/*Creamos el mosaico*/
			Mosaico mosaico = new Mosaico(11, 24);
			Console.WriteLine(mosaico);
			Console.WriteLine(" ");
			Console.WriteLine(" ");

			List<Color> colorsitos = new List<Color>();
			colorsitos.Add(Color.Verde);
			colorsitos.Add(Color.Azul);
			colorsitos.Add(Color.Rojo);

			Dictionary<Provincia, Color> diccionario = mapa.coloreadoRestricted(colorsitos);

			foreach (Provincia provincia in mapa.provincias)
			{
				mosaico = new Mosaico(mosaico.mosaico, mosaico.filas, mosaico.columnas, provincia, diccionario[provincia]);
				Console.WriteLine(mosaico);
				Console.WriteLine(" ");
				Console.WriteLine(" ");
			}

			Console.ReadLine();

		}

	}
}

/*
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................



........................
........................
........................
........................
........................
...VV...................
...VV...................
...VV...................
........................
........................
........................



........................
........................
........................
........................
........................
...VV...................
...VV...................
...VVAAA................
.....AAA................
........................
........................



........................
........................
........................
........................
.....RRRRR..............
...VVRRRRR..............
...VVRRRRR..............
...VVAAA................
.....AAA................
........................
........................



........................
........................
........................
........................
.....RRRRR..............
...VVRRRRR..............
...VVRRRRR..............
...VVAAAVVVVVVVV........
.....AAAVVVVVVVV........
........................
........................



........................
........................
........................
........................
.....RRRRR..............
...VVRRRRRAAAAAA........
...VVRRRRRAAAAAA........
...VVAAAVVVVVVVV........
.....AAAVVVVVVVV........
........................
........................



........................
........................
............VVVV........
............VVVV........
.....RRRRR..VVVV........
...VVRRRRRAAAAAA........
...VVRRRRRAAAAAA........
...VVAAAVVVVVVVV........
.....AAAVVVVVVVV........
........................
........................



........................
........................
............VVVV........
............VVVVRRR.....
.....RRRRR..VVVVRRR.....
...VVRRRRRAAAAAARRR.....
...VVRRRRRAAAAAARRR.....
...VVAAAVVVVVVVVRRR.....
.....AAAVVVVVVVV........
........................
........................



........................
........................
............VVVV........
............VVVVRRR.....
.....RRRRR..VVVVRRR.....
...VVRRRRRAAAAAARRRVVV..
...VVRRRRRAAAAAARRRVVV..
...VVAAAVVVVVVVVRRRVVV..
.....AAAVVVVVVVV........
........................
........................ 
*/